name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  testEmscriptenNode:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://trzeci/emscripten:latest     

    - name: make vendor_js
      run: make vendor_js
        
    - name: Make using emscripten image
      run: docker run -v $(pwd):/src trzeci/emscripten make js

    - name: Make run_js
      run: make run_js

  testEmscriptenWeb:

    runs-on: ubuntu-latest

    steps:
    - name: npm run build
      working-directory: ./packages/neopt-cpp-lib-js/
      run: npm run build

  testC:
    
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v2
      
    - name: make vendor_cpp
      run: make vendor_cpp
      
    - name: make
      run: make
      
    - name: make test
      run: make test
