name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  testEmscripten:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://trzeci/emscripten:latest     

    - name: make vendor_js
      run: make vendor_js
        
    - name: Make using emscripten image
      run: docker run -v $(pwd):/src trzeci/emscripten make js

    - name: Make runjs
      run: make runjs

  testC:
    
    runs-on: ubuntu-latest    
    
    steps:
    - uses: actions/checkout@v2
      
    - name: make vendor_cpp
      run: make vendor_cpp
      
    - name: make
      run: make
      
    - name: make test
      run: make test
